name: CI

on:
  pull_request:
  push:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: book.settings
      USE_SQLITE: "true"
      DEBUG: "True"

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Criar .env para CI
        run: |
          echo "DEBUG=True" >> .env
          echo "SECRET_KEY=ci-secret-key" >> .env
          echo "USE_SQLITE=true" >> .env
          echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> .env

      - name: Django check
        run: poetry run python manage.py check

      - name: Rodar migrações (SQLite)
        run: poetry run python manage.py migrate
